# -*- coding: utf-8 -*-
# Generated by Django 1.11.3 on 2017-10-13 18:57
from __future__ import unicode_literals

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Activities',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('activity_id', models.IntegerField(default=0)),
                ('activity_name', models.CharField(max_length=64)),
                ('group_number', models.IntegerField(default=1)),
                ('week_number', models.IntegerField(default=1)),
                ('employee_id', models.ForeignKey(default=0, on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
        ),
        migrations.CreateModel(
            name='Events',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('event_id', models.IntegerField(default=0)),
                ('event_name', models.CharField(max_length=256)),
                ('event_date', models.DateField()),
                ('time_start', models.DateTimeField()),
                ('time_end', models.DateTimeField()),
                ('hex_id', models.IntegerField(default=0)),
                ('event_comment', models.CharField(max_length=256)),
                ('employee_id', models.ForeignKey(default=0, on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
        ),
        migrations.CreateModel(
            name='Grades',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('attendance', models.BooleanField()),
                ('grade', models.IntegerField(default=0)),
                ('event_id', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='sap_Academy.Events')),
            ],
        ),
        migrations.CreateModel(
            name='Notes',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=32)),
                ('content', models.CharField(max_length=256)),
                ('note_date', models.DateField()),
            ],
        ),
        migrations.CreateModel(
            name='Students',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('sap_id', models.IntegerField(default=0)),
                ('first_name', models.CharField(max_length=64)),
                ('last_name', models.CharField(max_length=64)),
                ('email_address', models.CharField(max_length=128)),
                ('group_number', models.IntegerField(default=1)),
                ('territory', models.CharField(max_length=16)),
                ('country', models.CharField(max_length=16)),
                ('training_program', models.CharField(max_length=128)),
                ('employee_id', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
        ),
        migrations.AddField(
            model_name='grades',
            name='sap_id',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='sap_Academy.Students'),
        ),
    ]
